// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../../../nodejs/middleware/redirect/page.js'
export { default } from '../../../nodejs/middleware/redirect/page.js'
export const runtime = 'edge'
