// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../nodejs/layout.js'
export { default } from '../nodejs/layout.js'
export const runtime = 'edge'
