// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../../../nodejs/interrupted/throws-error/page.js'
export { default } from '../../../nodejs/interrupted/throws-error/page.js'
export const runtime = 'edge'
