// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../../../nodejs/[id]/setting-cookies/page.js'
export { default } from '../../../nodejs/[id]/setting-cookies/page.js'
export const runtime = 'edge'
