// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

'use client'
export * from '../../../nodejs/interrupted/calls-redirect/redirect.js'
export const runtime = 'edge'
