// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../../nodejs/provided-request-context/page.js'
export { default } from '../../nodejs/provided-request-context/page.js'
export const runtime = 'edge'
