// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

export * from '../../nodejs/delay/page.js'
export { default } from '../../nodejs/delay/page.js'
export const runtime = 'edge'

export const dynamic = 'force-dynamic'
