// This file was generated by the 'generate-edge-test-files' script.
// Do not edit it manually.

// 'use client'
export * from '../../nodejs/invalid-in-client/page.js'
export { default } from '../../nodejs/invalid-in-client/page.js'
export const runtime = 'edge'

export const dynamic = 'force-dynamic'
